# Generated by Django 5.1.5 on 2025-01-26 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0007_remove_question_question_text_remove_quiz_challenge_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='description',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='title',
        ),
        migrations.AddField(
            model_name='quiz',
            name='challenge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='challenges.challenge', verbose_name='Челлендж'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='name',
            field=models.CharField(default='Default Quiz Name', max_length=255, verbose_name='Название'),
        ),
    ]
