# Generated by Django 5.1.5 on 2025-01-27 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0011_audiochallenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiochallenge',
            name='challenge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='challenges.challenge'),
        ),
    ]
