# Generated by Django 5.1.5 on 2025-01-27 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0012_audiochallenge_challenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiochallenge',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='audio_challenge_images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='audiochallenge',
            name='challenge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audio_challenges', to='challenges.challenge', verbose_name='Челлендж'),
        ),
        migrations.AlterField(
            model_name='audiochallenge',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
