# Generated by Django 5.1.5 on 2025-01-27 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0013_audiochallenge_image_alter_audiochallenge_challenge_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiochallenge',
            name='audio_file',
        ),
        migrations.RemoveField(
            model_name='audiochallenge',
            name='correct_answer',
        ),
        migrations.CreateModel(
            name='AudioTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='audio_tracks/')),
                ('correct_answer', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField()),
                ('audio_challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_tracks', to='challenges.audiochallenge')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
