# Generated by Django 5.1.5 on 2025-01-27 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0014_remove_audiochallenge_audio_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiochallenge',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='audio_challenges/'),
        ),
        migrations.AddField(
            model_name='audiochallenge',
            name='correct_answer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='AudioTrack',
        ),
    ]
