# Generated by Django 5.1.5 on 2025-01-28 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0016_dailycoupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailycoupon',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
