# Generated by Django 4.2.18 on 2025-02-03 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0018_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='coupon_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_images', to='challenges.challenge')),
            ],
        ),
    ]
