# Generated by Django 4.2.18 on 2025-02-04 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0019_couponimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiochallenge',
            name='audio_file',
        ),
        migrations.RemoveField(
            model_name='audiochallenge',
            name='correct_answer',
        ),
        migrations.RemoveField(
            model_name='audiochallenge',
            name='image',
        ),
        migrations.AlterField(
            model_name='audiochallenge',
            name='challenge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audio_challenges', to='challenges.challenge', verbose_name='Челлендж'),
        ),
        migrations.AlterField(
            model_name='audiochallenge',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='audiochallenge',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.CreateModel(
            name='AudioQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='audio_questions/')),
                ('correct_answer', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('audio_challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='challenges.audiochallenge')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
